name: "Artillery load testing action"
author: Artillery
description: "Load testing of your application at scale."

inputs:
  command:
    required: true
    description: "Artillery CLI command to execute"
  working-directory:
    description: "Custom working directory for Artillery commands"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    CWD: ${{ inputs.working-directory }}
  args:
    - ${{ inputs.command }}

branding:
  icon: zap
  color: gray-dark
