name: "Artillery load testing action"
author: Artillery
description: "Load testing of your application at scale."

inputs:
  command:
    required: true
    description: "Artillery CLI command to execute"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}

branding:
  icon: zap
  color: gray-dark
